# Массивы

In [1]:
import numpy as np
a = np.zeros((2, 3), dtype=np.float32) # create an array filled 0
a

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [2]:
type(a)

numpy.ndarray

In [3]:
a = np.zeros((2, 3, 4), dtype=np.float32); a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)

In [4]:
a += 1; a

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

In [5]:
a *= 2; a

array([[[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]]], dtype=float32)

In [6]:
ones = lambda *shape: np.ones(shape, dtype=np.float32)

In [7]:
ones(1, 3, 4) # shape = (1, 3, 4)

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

# Задача
### Красиво вывести операцию A + B = С на экран

In [10]:
def operation_print(*expression):
  lines = [str(x).split('\n') for x in expression]
  max_lines = max(len(x) for x in lines)
  max_widths = [max(len(y) for y in x) for x in lines]
  lines = [line + [' '] * (max_lines - len(line)) for line in lines]
  lines = [[y + ' '*(max_widths[i] - len(y)) if i % 2 == 0 else y for y in x] for i, x in enumerate(lines)]
  lines = np.array(lines).T
  lines = '\n'.join([' '.join(line) for line in lines])
  print(lines)


In [11]:
operation_print(ones(5, 2), '+', ones(5, 2), '=', ones(5, 2) * 2)

[[1. 1.]  + [[1. 1.]  = [[2. 2.] 
 [1. 1.]     [1. 1.]     [2. 2.] 
 [1. 1.]     [1. 1.]     [2. 2.] 
 [1. 1.]     [1. 1.]     [2. 2.] 
 [1. 1.]]    [1. 1.]]    [2. 2.]]


In [12]:
A = np.arange(1, 11).reshape(5,2)
B = np.linspace(10, 30, 10).reshape(5,2)
R = A * B
operation_print(A, '*', B, '=', R)

[[ 1  2]  * [[10.         12.22222222]  = [[ 10.          24.44444444] 
 [ 3  4]     [14.44444444 16.66666667]     [ 43.33333333  66.66666667] 
 [ 5  6]     [18.88888889 21.11111111]     [ 94.44444444 126.66666667] 
 [ 7  8]     [23.33333333 25.55555556]     [163.33333333 204.44444444] 
 [ 9 10]]    [27.77777778 30.        ]]    [250.         300.        ]]


In [13]:
class Op:
  def __init__(self, name, func):
    self.name = name
    self.func = func

  def __call__(self, x, y):
    r = self.func(x, y)
    operation_print(x, self.name, y, '=', r)

In [14]:
Add = Op('+', lambda x, y: x + y)
Add(A, B)

[[ 1  2]  + [[10.         12.22222222]  = [[11.         14.22222222] 
 [ 3  4]     [14.44444444 16.66666667]     [17.44444444 20.66666667] 
 [ 5  6]     [18.88888889 21.11111111]     [23.88888889 27.11111111] 
 [ 7  8]     [23.33333333 25.55555556]     [30.33333333 33.55555556] 
 [ 9 10]]    [27.77777778 30.        ]]    [36.77777778 40.        ]]


In [15]:
Mul = Op('*', lambda x, y: x * y)
Mul(A, B)

[[ 1  2]  * [[10.         12.22222222]  = [[ 10.          24.44444444] 
 [ 3  4]     [14.44444444 16.66666667]     [ 43.33333333  66.66666667] 
 [ 5  6]     [18.88888889 21.11111111]     [ 94.44444444 126.66666667] 
 [ 7  8]     [23.33333333 25.55555556]     [163.33333333 204.44444444] 
 [ 9 10]]    [27.77777778 30.        ]]    [250.         300.        ]]


In [16]:
MMul = Op('@', lambda x, y: x @ y)
MMul(A.T, B)

[[ 1  3  5  7  9]  @ [[10.         12.22222222]  = [[561.11111111 616.66666667] 
 [ 2  4  6  8 10]]    [14.44444444 16.66666667]     [655.55555556 722.22222222]]
                      [18.88888889 21.11111111]                                 
                      [23.33333333 25.55555556]                                 
                      [27.77777778 30.        ]]                                


# Индексация

In [17]:
B

array([[10.        , 12.22222222],
       [14.44444444, 16.66666667],
       [18.88888889, 21.11111111],
       [23.33333333, 25.55555556],
       [27.77777778, 30.        ]])

In [18]:
B[0] # первая строка

array([10.        , 12.22222222])

In [19]:
B[:, 0] # первый столбец

array([10.        , 14.44444444, 18.88888889, 23.33333333, 27.77777778])

# Broadcasting and stack

In [21]:
Add(A, B[0])

[[ 1  2]  + [10.         12.22222222] = [[11.         14.22222222] 
 [ 3  4]                                 [13.         16.22222222] 
 [ 5  6]                                 [15.         18.22222222] 
 [ 7  8]                                 [17.         20.22222222] 
 [ 9 10]]                                [19.         22.22222222]]


In [22]:
Mul(A, B[0])

[[ 1  2]  * [10.         12.22222222] = [[ 10.          24.44444444] 
 [ 3  4]                                 [ 30.          48.88888889] 
 [ 5  6]                                 [ 50.          73.33333333] 
 [ 7  8]                                 [ 70.          97.77777778] 
 [ 9 10]]                                [ 90.         122.22222222]]


In [32]:
np.stack(list(B[0:1]) * 5)

array([[10.        , 12.22222222],
       [10.        , 12.22222222],
       [10.        , 12.22222222],
       [10.        , 12.22222222],
       [10.        , 12.22222222]])

# Бинарные и логические операции

In [33]:
A

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [34]:
A > 3

array([[False, False],
       [False,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [35]:
B

array([[10.        , 12.22222222],
       [14.44444444, 16.66666667],
       [18.88888889, 21.11111111],
       [23.33333333, 25.55555556],
       [27.77777778, 30.        ]])

In [36]:
np.isclose(B, 10)

array([[ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False]])

In [37]:
idx = np.isclose(B, 10) | np.isclose(B, 30)
B[idx]

array([10., 30.])